# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hrubiecKatherine_GetMeThere' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hrubiecKatherine_GetMeThere
        pod 'Firebase/Core'
        pod 'Firebase/Auth'
        pod 'Firebase/Database'
	pod 'GoogleMaps'

  target 'hrubiecKatherine_GetMeThereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hrubiecKatherine_GetMeThereUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
